changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: New Features / 新功能
      labels:
        - enhancement
        - feature
    - title: Fixes / 修复
      labels:
        - bug
        - fix
    - title: Documentation / 文档
      labels:
        - documentation
        - docs
    - title: Maintenance / 维护
      labels:
        - chore
        - ci
        - dependencies
